Based on the previous requests, it seems like there is a duplicate request for creating a YAML workflow to clone a specific repository. To avoid redundancy, I will provide you with a single YAML workflow that accomplishes this task:

```yaml
name: Clone Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  clone_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Repository
        run: git clone https://github.com/vccaso/avila-easychat.git ./workspace/avila-easychat
```

You can use this YAML workflow to clone the repository `https://github.com/vccaso/avila-easychat.git` and save it to `./workspace/avila-easychat` whenever a push event occurs on the `main` branch. Let me know if you need any further assistance or modifications.