name: code_generator_workflow
description: this workflow generate code for CRUD

vars:
  local_repo_dir: ./workspace/avila-easychat-goals
  source_branch: dev
  branch_name: comments
  repo_name: avila-easychat-goals

steps:

  - name: clone_repo
    type: git
    agent: GitHubCloneOrUpdateRepoAgent
    input:
      repo_url: https://github.com/vccaso/avila-easychat-goals.git
      local_repo_dir: ${local_repo_dir}

  - name: checkout branch
    type: git
    agent: GitHubCheckoutBranchAgent
    input:
      source_branch: ${source_branch}
      local_repo_dir: ${local_repo_dir}

  - name: create branch
    type: git
    agent: GitHubCreateBranchAgent
    input:
      branch_name: ${branch_name}
      local_repo_dir: ${local_repo_dir}

  - name: generate_code
    type: ai
    agent: GoSwaggerAgent
    model: ModelGpt35Turbo
    input:
      local_repo_dir: ${local_repo_dir}

  - name: stage_commit_push
    type: git
    agent: GitHubCommitAgent
    input:
      new_branch: ${branch_name}
      local_repo_dir: ${local_repo_dir}
      commit_message: "Swagger comments code added"

  - name: stage_commit_push
    type: git
    agent: GitHubPRAgent
    input:
      repo_name: ${repo_name}
      pr_title: "Swagger comments code added"
      new_branch: ${branch_name}
      source_branch: ${source_branch}
      pr_body: "Swagger comments code added"
