alerts:
  - name: high_cpu_alert
    condition: "80 > 70"  # Example placeholder; in practice use a real metric check
    interval: 10  # Check every 60 seconds
    cooldown: 25
    actions:
      - agent: GenericEmailAgent
        input:
          sender: "vccaso@gmail.com"
          recipient: "vccaso@gmail.com"
          subject: "Alert from GCG"
          body: |
            this is a test alert from GCG
            used from GenericEmailAgent
          password: ${EMAIL_PASSWORD}
